version: "3"

services:
    restapi:
        build: ./RESTAPI
        depends_on: 
            - mongo
        environment:
          - PORT=5000
          - MONGO_URI=mongodb://mongo:27017/dbFacultadAct
          - SECRET=facci2022
    estudiantessr:
        build: ./EstudianteSSR
        depends_on: 
            - mongo
        environment:
          - PORT=8000
          - MONGO_URI=mongodb://mongo:27017/dbFacultadAct
          - API=http://restapi:5000/api
          - SECRET=facci2022
    microservicio1:
        build: ./microservicio1
        depends_on: 
            - mongo
        environment:
          - MONGO_URI=mongodb://mongo:27017/dbFacultadAct
    nginx:
        image: nginx:latest
        ports:
            - "7000:7000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - restapi
            - estudiantessr
    mongo:
        image: mongo
